version: '2'

services:

  mysql:
    build:
      context: ./mysql
      dockerfile: Dockerfile
    volumes:
      - "/home/ITRANSITION.CORP/a.ganetsky/dockerAll/mysql:/var/lib/mysql" 

  web:
    build:
      context: ./apache
      dockerfile: Dockerfile
    volumes:
      - "./apache/www:/var/www"
    ports:
      - "80:80" 
    links: 
      - mysql