version: '2'
services:
  mysql:
    build:
      context: ./mysql
      dockerfile: Dockerfile
  web:
    build:
      context: ./apache
      dockerfile: Dockerfile
    volumes:
      - "./apache/html:/var/www/html"
    ports:
      - "80:80" 
    links:
      - mysql