version: '2'

services:

  mysql:
    build:
      context: ./mysql
      dockerfile: Dockerfile
    volumes:
      - "./mysql/mysql:/var/lib/mysql" 
  
  web:
    build:
      context: ./apache
      dockerfile: Dockerfile
    volumes:
      - "./apache/html:/var/www"
    ports:
      - "80:80" 
    depends_on: 
      - mysql